- title: Notebook example in config 2
  description: Example of opening a notebook in dashboard mode without Voila
  source: ./sample.ipynb
  cwd: '.'
  type: notebook
  catalog: Config 2

- title: Markdown
  description: Example of opening a markdown file
  source: ./beam.md
  cwd: '.'
  type: markdown
  catalog: Config 2

- title: Command example 2
  description: Example of calling JupyterLab commands
  type: jupyterlab-commands
  source:
    - label: Command 1
      id: 'filebrowser:open-path'
      args:
        path: sample.ipynb
  cwd: '.'
  catalog: Config 2
