# a mybinder.org-ready environment for demoing jupyter_app_launcher
# this environment may also be used locally on Linux/MacOS/Windows, e.g.
#
#   conda env update --file binder/environment.yml
#   conda activate jupyterlab-app-launcher-demo
#
name: jupyterlab-app-launcher-demo

channels:
  - conda-forge

dependencies:
  # runtime dependencies
  - python >=3.8,<3.9.0a0
  - jupyterlab >=3,<4.0.0a0
  # labextension build dependencies
  - nodejs >=14,<15
  - pip
  - wheel
  - ipywidgets
  - ipyflex
  - voila
  - voila-gridstack
  - ipyleaflet
  - streamlit=1.11.1
  - pandas
  - numpy
  - cosapp
  - plotly
  - ipyvuetify
